// React/001 - React Start/projeto/src/componentes/Form.js
import {useState} from 'react'

function Form(){
    function cadastroUsuario(e){
        e.preventDefault()
        console.log(name)
        console.log(senha)
    }
    const [name, setName] = useState()
    const [senha, setSenha] = useState()
    return(
        <div>
            <h1>Testando Formulário:</h1>
            <form onSubmit={cadastroUsuario}>
                <div>
                    <label htmlFor="user">Usuário: </label>
                    <input
                        type="text"
                        id="user"
                        name="user"
                        placeholder="Digite o seu nome"
                        onChange={(e) => setName(e.target.value)}/>
                </div>
                <div>
                    <label htmlFor="senha">Senha: </label>
                    <input
                        type="password"
                        id="senha"
                        name="senha"
                        placeholder="Digite sua senha"
                        onChange={(e) => setSenha(e.target.value)}/>
                </div>
                <button>Cadastrar usuário</button>
            </form>
        </div>
    )
}

export default Form

// JavaScript VUE/VUE Course/003 - Utilizando o Vue CLI/2_projeto_vue/src/components/Form.vue
<template>
    <h2>Meu Formulário</h2>
    <form action="post">
        <input type="text" placeholder="Usuário">
        <input type="text" placeholder="Seu email">
        <input type="submit" value="Enviar">
    </form>
</template>

<script>
    export default{
        name: 'Form'
    }
</script>
